### ISSUE TITLE
文件长度错误！

### ISSUE THREAD

**Issue by sshwy** [cqjjjzr/LCSELocalizationTools#2]
运行时出现了文件长度错误的信息，想请教一下这是为什么，以及有没有解决的方法

```
LC-ScriptEngine资源包封包处理实用工具 rv1
        By Charlie Jiang


Exception in thread "main" java.lang.IllegalArgumentException: 文件长度错误！
        at charlie.lcsetools.pkgutil.LCSEIndexList$Companion.readFromBuffer(LCSEPackage.kt:38)
        at charlie.lcsetools.pkgutil.LCSEPackageMainKt.main(LCSEPackageMain.kt:47)
```

**Comment by sshwy** [comment]
另外问一下snx脚本该怎么处理啊

**Comment by cqjjjzr** [comment]
能提供一下游戏名称吗..

**Comment by sshwy** [comment]
大催眠乱交学園 ～学園は乱交催眠の洗脳教育実験場～

**Comment by cqjjjzr** [comment]
我怀疑是该游戏加密lcsebody数据包的时候xor的数不同，请问方便换到更实时的交流工具（QQ/TG）吗？

**Comment by sshwy** [comment]
可以啊。QQ 1272918035 尧尧
